### ISSUE TITLE
Реализовать frontend

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWeb#10]
Необходимо реализовать frontend часть по обговорённой на встрече схеме. Диаграмма ниже. Так же она представлена в репозитории NorthGateWiki.

Всё взаимодействие идёт с API по принципу описанному в задаче [Реализовать API Backend-а](https://github.com/NorthGateVologda/NorthGateBackend/issues/14).

В реализации необходимо полагаться на результаты задачи [Написать User Story](https://github.com/NorthGateVologda/NorthGate/issues/5). В рамках её же будут макеты экранов.

Задача декомпозируется на следующие этапы:

- [x] реализовать выборку города с помощью выпадающих списков
- [ ] реализовать всю схему выборки и сохранения слоёв

Первый этап включает в себя минимализм:

1. Система авторизации
2. Выпадающий список населённых пунктов с поиском
3. При выборе населённого пункта появляется мультиполигон данного пункта вмещающийся в экран
4. При каждом новом выпадающем списке, каждый список имеет пустое значение, которое является выбранным
5. При изменении нп, собственно говоря экран обновляется с новым нп
6. При изменении района, карта не меняется, но список с нп обновляется с выбранным пустым значением
7. При выборе значения нп появляется мультиполигон данного пункта вмещающийся в экран
8. При изменении области исчезает выпадающий список нп, список районов обновляется, карта не изменяется
9. При выборе района появляется список с нп, карта всё ещё не меняется
20. При выборе значения нп появляется мультиполигон данного пункта вмещающийся в экран

Для этого этапа **НЕ СТОИТ** ждать макетов экрана!

Для второго этапа необходимы макеты экрана с упомянутой задачи (@Malaxov16)

![Image](https://github.com/NorthGateVologda/NorthGateWeb/assets/13800244/056c5769-50c1-4fb2-a236-fcdbc03d0e91)

**Comment by sshiae** [comment]
@bagkir @lvapl не ждите user story, так то уже можно что то накидывать, ребята там уже макет сделали, хотя бы начинать уже проект готовить, подключать различные модули, пробовать верстать уже

**Comment by lvapl** [comment]
Да, начинаю. Я буду полностью с нуля переделывать и использовать framework Next js

**Comment by olgapshen** [comment]
Поведение фронтенда немного изменилось в связи составленным User Story.
Теперь у нас не многоступенчатая выборка НП а сразу в поиске по частью имени.
Я позже актуализирую схему поведения.

@lvapl cинхронизируйся по поведению frontend-а у @Malaxov16 м @Marwin887

**Comment by olgapshen** [comment]
@lvapl @Marwin887 @sshiae @Malaxov16 проговорили сегодня с Витей, решили реанимировать контур с NodeJS и добавить вывод домов, к выводу тур объектов. В интерфейсе будет радио или выпадающий список где можно будет выбрать, что мы хотим отобразить.

После прохождения данного этапа продолжим перевод фронтэнда на Next JS.

**Comment by lvapl** [comment]
@olgapshen, @sshiae эту задачу оставляем на следующий этап или новую ставить будем?

**Comment by olgapshen** [comment]
Давайте новую поставим. У нас будет совершенно иное поведение фронта.

**Comment by olgapshen** [comment]
@Marwin887 и @Malaxov16 надежда на вас, в плане постановки задачи для фронтенда.

**Comment by Marwin887** [comment]
@olgapshen У нас есть User story и макет экрана, могу описать еще отдельно по функциям, если есть вопросы.

**Comment by olgapshen** [comment]
> @olgapshen У нас есть User story и макет экрана, могу описать еще отдельно по функциям, если есть вопросы.

Это к @sshiae и @lvapl
