### ISSUE TITLE
Язык README

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateWeb#21]
Надо будет в README как то добавить информацию о том, что это именно наш проект, там добавить "Врата Севера" в заголовок. Надо решить очень важную вещь. На каком языке писать документацию.

_Originally posted by @olgapshen in https://github.com/NorthGateVologda/NorthGateWeb/pull/19#discussion_r1285247084_

**Comment by lvapl** [comment]
Думаю сейчас будет лучше на русском языке. А этот текст был сгенерирован Next js, я его перепишу

**Comment by sshiae** [comment]
Тоже так считаю

**Comment by olgapshen** [comment]
Ладно, зафиксируем этот момент [тут](https://github.com/NorthGateVologda/NorthGate/issues/42)
